"""create tickets table

Revision ID: 4107a50a2d57
Revises: d1383c02f745
Create Date: 2026-07-22 16:30:24.259149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4107a50a2d57'
down_revision: Union[str, Sequence[str], None] = 'd1383c02f745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'email')
    # ### end Alembic commands ###
